apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-poc-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-poc-webapp
  template:
    metadata:
      labels:
        app: argocd-poc-webapp
    spec:
      containers:
      - name: nginx
        image: asoltes/nginx-argocd-poc:v1.0.0
        ports:
        - containerPort: 80
