apiVersion: v1
kind: Service
metadata:
  name: argocd-poc-webapp-service
  namespace: argocd-poc-namespace
spec:
  selector:
    app: argocd-poc-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
